In [1]:
# 필요한 모듈 임포트
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
# 모델의 정확도 평가를 위해 임포트합니다
from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/drive/MyDrive/기말시험/201937006_김준기/bank.csv")

#수집된 데이터 샘플 확인
df.head(15) # 처음 15개의 데이터만 입력

                                            customers    y
0   unemployed married primary no no cellular unknown   no
1   services married secondary yes yes cellular fa...   no
2   management single tertiary yes no cellular fai...   no
3   management married tertiary yes yes unknown un...   no
4   blue-collar married secondary yes no unknown u...   no
5   management single tertiary no no cellular failure   no
6   self-employed married tertiary yes no cellular...   no
7   technician married secondary yes no cellular u...   no
8   entrepreneur married tertiary yes no unknown u...   no
9   services married primary yes yes cellular failure   no
10  services married secondary yes no unknown unknown   no
11   admin. married secondary yes no cellular unknown   no
12  technician married tertiary no no cellular unk...   no
13    student single secondary no no cellular unknown  yes
14  blue-collar married secondary yes yes cellular...   no

In [2]:
df['label'] = df['y'].map({"yes":1,"no":0})

In [3]:
X_df = df['customers']
Y_df = df['label']
print(X_df)

0       unemployed married primary no no cellular unknown
1       services married secondary yes yes cellular fa...
2       management single tertiary yes no cellular fai...
3       management married tertiary yes yes unknown un...
4       blue-collar married secondary yes no unknown u...
                              ...
4516    services married secondary yes no cellular unk...
4517    self-employed married tertiary yes yes unknown...
4518    technician married secondary no no cellular un...
4519    blue-collar married secondary no no cellular o...
4520    entrepreneur single tertiary yes yes cellular ...
Name: customers, Length: 4521, dtype: object

In [4]:
train,test=train_test_split(df,test_size=0.3)

In [5]:
# 다항분포 나이브 베이즈 분류기의 입력 데이터(영화 리뷰)는 고정된 크기의 벡터이여야함.
# 입력 데이터를 모두 고정 길이로 만들기
cv = CountVectorizer() # ★★binary = True 가 없기 때문에 출현 횟수로 저장★★
x_traincv = cv.fit_transform(X_df)

# 전체 고정 벡터 인덱스의 단어 출력(한 글자 단어는 제외됨. 예.I)
cv.get_feature_names()

['admin',
 'blue',
 'cellular',
 'collar',
 'divorced',
 'employed',
 'entrepreneur',
 'failure',
 'housemaid',
 'management',
 'married',
 'no',
 'other',
 'primary',
 'retired',
 'secondary',
 'self',
 'services',
 'single',
 'student',
 'success',
 'technician',
 'telephone',
 'tertiary',
 'unemployed',
 'unknown',
 'yes']

In [6]:
#인코딩 벡터 확인
encoded_input=x_traincv.toarray()
encoded_input
cv.inverse_transform(encoded_input[0])

[array(['cellular', 'married', 'no', 'primary', 'unemployed', 'unknown'],
       dtype='<U12')]

In [7]:
# 학습 데이터로 다항분포 분류기 학습
# 사이킷런의 다항분포 나이브 베이즈는 스무딩을 기본 지원함
mnb = MultinomialNB()
mnb.fit(x_traincv,Y_df) # 다항분포 분류기 학습 실행

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [11]:
test = pd.DataFrame(df)
test['label'] = test['y'].map({"yes":1,"no":0})
test_x=test["customers"]
test_y=test['label']
x_testcv=cv.transform(test_x) # 고정 크기 벡터로 변환

In [12]:
# 테스트 데이터에 대해 예측 실행
predictions = mnb.predict(x_testcv)
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
# 모델 예측 정확도(accuracy) 출력
accuracy = accuracy_score(test_y,predictions)
if accuracy ==1:
    print("accuracy : 100%")
else:
    print("accuracy : %.2f" %(accuracy_score(test_y,predictions)*100)+"%")

accuracy : 89.36%